// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sgen

import (
	"time"
)

type User struct {
	ID           int64     `json:"id"`
	Pid          string    `json:"pid"`
	Phone        string    `json:"phone"`
	CountryCode  string    `json:"country_code"`
	PasswordHash string    `json:"password_hash"`
	Validated    bool      `json:"validated"`
	Version      int32     `json:"version"`
	UpdatedAt    time.Time `json:"updated_at"`
	CreatedAt    time.Time `json:"created_at"`
}
