// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"database/sql"
	"time"
)

type AuthnType struct {
	ID        int64          `json:"id"`
	Type      sql.NullString `json:"type"`
	Version   int32          `json:"version"`
	UpdatedAt time.Time      `json:"updated_at"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID           int64          `json:"id"`
	Pid          string         `json:"pid"`
	AuthnType    sql.NullString `json:"authn_type"`
	Email        sql.NullString `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Validated    bool           `json:"validated"`
	Version      int32          `json:"version"`
	UpdatedAt    time.Time      `json:"updated_at"`
	CreatedAt    time.Time      `json:"created_at"`
}
