// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
	"time"
)

type AppConfiguration struct {
	ID        int64          `json:"id"`
	Name      sql.NullString `json:"name"`
	Scope     sql.NullString `json:"scope"`
	TextValue string         `json:"text_value"`
	Version   int32          `json:"version"`
	UpdatedAt time.Time      `json:"updated_at"`
	CreatedAt time.Time      `json:"created_at"`
}

type Authn struct {
	ID         int32          `json:"id"`
	CustomerID sql.NullInt32  `json:"customer_id"`
	Type       sql.NullString `json:"type"`
	RefID      sql.NullInt32  `json:"ref_id"`
	Version    int32          `json:"version"`
	UpdatedAt  time.Time      `json:"updated_at"`
	CreatedAt  time.Time      `json:"created_at"`
}

type AuthnEmail struct {
	ID           int32          `json:"id"`
	Email        sql.NullString `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Activated    bool           `json:"activated"`
	Version      int32          `json:"version"`
	UpdatedAt    time.Time      `json:"updated_at"`
	CreatedAt    time.Time      `json:"created_at"`
}

type AuthnType struct {
	ID        int32          `json:"id"`
	Type      sql.NullString `json:"type"`
	Version   int32          `json:"version"`
	UpdatedAt time.Time      `json:"updated_at"`
	CreatedAt time.Time      `json:"created_at"`
}

type Config struct {
	ID        int32          `json:"id"`
	Pid       string         `json:"pid"`
	Name      sql.NullString `json:"name"`
	Type      sql.NullString `json:"type"`
	Version   int32          `json:"version"`
	UpdatedAt time.Time      `json:"updated_at"`
	CreatedAt time.Time      `json:"created_at"`
}

type ConfigScope struct {
	ID        int32          `json:"id"`
	Scope     sql.NullString `json:"scope"`
	Version   int32          `json:"version"`
	UpdatedAt time.Time      `json:"updated_at"`
	CreatedAt time.Time      `json:"created_at"`
}

type ConfigType struct {
	ID        int32          `json:"id"`
	Type      sql.NullString `json:"type"`
	Version   int32          `json:"version"`
	UpdatedAt time.Time      `json:"updated_at"`
	CreatedAt time.Time      `json:"created_at"`
}

type Customer struct {
	ID        int32          `json:"id"`
	Pid       string         `json:"pid"`
	Email     sql.NullString `json:"email"`
	Version   int32          `json:"version"`
	UpdatedAt time.Time      `json:"updated_at"`
	CreatedAt time.Time      `json:"created_at"`
}
