name: ars

networks:
  network:
    external: false

secrets:
  postgres_root_password:
    file: ./secret/postgres_root_password.txt
  postgres_user_password:
    file: ./secret/postgres_user_password.txt

volumes:
  mongo_data:
  postgres_data:
  redis_data:
  localstack_data:


services:

#   localstack:
#     container_name: ars_localstack
#     image: localstack/localstack
#     ports:
#       - "4566:4566"            # LocalStack Gateway
#       - "4510-4559:4510-4559"  # external services port range
#     # environment:
#       # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
#       # - DEBUG=${DEBUG:-0}
#     volumes:
#       # - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
#       - localstack_data:/var/lib/localstack
#       - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    networks:
      - network
    image: postgres:17.0
    container_name: ars_postgres
    ports:
      - '5432:5432'
    secrets:
      - postgres_root_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_root_password
    volumes:
      - postgres_data://var/lib/postgresql/data
      - ./postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/script/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10

  mongo:
    networks:
      - network
    image: mongodb/mongodb-community-server:latest
    container_name: ars_mongo
    ports:
      - '27017:27017'

  redis:
    networks:
      - network
    image: "redis:alpine"
    container_name: ars_redis
    ports:
      - '6379:6379'
